### PR TITLE
Added defaultValue to Property

### PR DESCRIPTION
**Pull request by jonasfj**
This is based on top of https://github.com/dart-lang/gcloud/pull/81 so feel free to ignore the first commit. It was just necessary for tests to have a change at passing.

### CODE REVIEW

**Comment by jonasfj** [comment]
I guess a possible downside is that this won't work well with indexing... Maybe we should force `indexed: false` when defaultValues are given.

**Comment by jonasfj** [comment]
/CC @isoos, I think we can do `defaultValue`, but I'm realizing it could be a foot gun, if users expects to be able to query properties with a default value... So maybe we shouldn't add it anyways?

**Comment by isoos** [comment]
I think it is still useful. We could provide a small utility class to scan the db and backfill properties without the set value.

**Comment by kevmoo** [comment]
@jonasfj – very stale, no?

**Comment by jonasfj** [comment]
Yeah, maybe one day we can revive it. But I think we should spend energy moving away from `dart:mirrors` before we add more features to datastore wrappers.

**Pull request closed without merging**
