### PR TITLE
Add possibility to define generic keys

### PR DESCRIPTION
**Pull request by enyo**
This is the updated PR for the changes we discussed in https://github.com/dart-lang/gcloud/pull/58

### CODE REVIEW

**Comment by isoos** [comment]
lgtm

**Comment by enyo** [comment]
Wow thanks for looking into it that fast. I've also changed the `fromDatastoreKey` function to include the generic type when converting a datastore key to a db key. This allows defining a model like this:

```dart
class User extends Model {
  @ModelKeyProperty()
  Key<String> countryKey;
}
```

Previously this would fail, because all `Key` values from the datastore where of type `Key<dynamic>` and couldn't automatically be casted.

**Comment by enyo** [comment]
I will now create a separate PR where the `Model` type is also added as a generic to the `Key` class to see whether this is more useful.

**Comment by enyo** [comment]
I've started implementing option 2, but ran into problems that I think aren't properly solvable with dart's current state.

The problem is, that when reading entities from the database in `fromDatastoreKey` (`model_db_impl.dart`), we have the type of the key model as `Type type`. To generate the key at this location we would need to write:

```dart
var type = _type2ModelDesc[_kind2ModelDesc[element.kind]];
// [...]
key = key.append<type, String>(id: elementId);
```
But obviously we can't use `type` here as a generic parameter.

Unless you have a suggestion on how to solve this issue, I think this option needs to be abandoned.

If you agree, should I update the CHANGELOG and `pubspec.yaml` or do you want to do this?

**Comment by enyo** [comment]
Oh and do you think it's a good idea to add a `key.cast<String>()` method, similar to `List.cast`?

**Comment by jonasfj** [comment]
> If you agree, should I update the CHANGELOG and pubspec.yaml or do you want to do this?

Please go for it :)

**Comment by enyo** [comment]
Ok, I pushed everything. I also added `Key.cast()` which allows to cast a `dynamic` key to a `String` or `int` one.

**Comment by enyo** [comment]
I've just seen that the tests didn't passt. It's due to the added `Key.cast` function. Do you want to keep the function, then I'll fix the test.

**Comment by jonasfj** [comment]
@enyo, I think it fine to drop the cast thing.. is it useful... Maybe for migrating legacy cases?

Either way, fix the test and I'll ship this :)

**Comment by enyo** [comment]
@jonasfj sorry it took me 5 months to actually fix that test, but everything should be in order now!

**Comment by enyo** [comment]
@kevmoo @jonasfj I fixed the merge conflicts. This is ready to go :)

**Comment by kevmoo** [comment]
@jonasfj should do the final review here

**Comment by jonasfj** [comment]
Sorry about the turn around time... I think my only concern is a breaking change in a package that has been stable for so long. But nothing is forcing people to upgrade right now.

**Comment by jonasfj** [comment]
Published as 0.7.0

**Comment by enyo** [comment]
> Sorry about the turn around time... I think my only concern is a breaking change in a package that has been stable for so long. But nothing is forcing people to upgrade right now.

Understandable! But I think that adding generic keys is definitely an upgrade.

**Pull request merged**
